version: '2'

services:
   elasticsearch:
     image: 'elasticsearch:6.6.0'
     ports:
       - 9200:9200

   kibana:
     image: 'kibana:6.6.0'
     ports:
       - 5601:5601

   mongodb:
     image: 'mongo'
     ports:
      - 27017:27017

   redis:
      image: 'redis'
      ports:
        - 6379:6379